version: 0.0
os: linux

files:
  - source: /app
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 20
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
